services:

# Keycloak service definition will be inherited from concrete clustering configurations.
  acme-keycloak:
    image: quay.io/keycloak/keycloak:$KEYCLOAK_VERSION
    user: "${USER}:${GROUP}"
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"

      KEYCLOAK_THEME_CACHING: "false"
      KEYCLOAK_THEME_TEMPLATE_CACHING: "false"
      PROXY_ADDRESS_FORWARDING: "true"

      DB_VENDOR: POSTGRES
      DB_ADDR: acme-keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DB_SCHEMA: public

      # Triggers Truststore generation and dynamic TlS certificate import
      X509_CA_BUNDLE: "/etc/x509/ca/*.crt"

      CACHE_OWNERS_COUNT: 2
      CACHE_OWNERS_AUTH_SESSIONS_COUNT: 2

#    # IntelliJ currently does not support the depends_on condition syntax
#    depends_on:
#      acme-keycloak-db:
#        condition: service_healthy
    volumes:
      - ./cli:/opt/jboss/startup-scripts:z
      # This configures the key and certificate for HTTPS.
      - ../../../config/stage/dev/tls/acme.test+1.pem:/etc/x509/https/tls.crt:z
      - ../../../config/stage/dev/tls/acme.test+1-key.pem:/etc/x509/https/tls.key:z
      # Allow TLS connection to ourself, this is necessary for cross realm Identity Brokering
      - ../../../config/stage/dev/tls/acme.test+1.pem:/etc/x509/ca/tls.crt:z
    ports:
      - "8080"
      - "8443"

  acme-keycloak-db:
    image: postgres:11.12
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./run/postgres/data:/var/lib/postgresql/data:z
