services:
  acme-keycloak:
    #image: quay.io/keycloak/keycloak:$KEYCLOAK_VERSION

    build:
      context: "./keycloakx"
      dockerfile: "./Dockerfile"

    #    user: "${USER}:${GROUP}"
    env_file:
      - ./keycloak-common.env
      - ./keycloak-http.env
    environment:
#      KC_DB: "dev-file"
#      KC_DB_USERNAME: "sa"
#      KC_DB_PASSWORD: ""
      KC_HTTP_RELATIVE_PATH: "/auth"

#      KC_METRICS_ENABLED: true

# see https://www.keycloak.org/server/features
#      KC_FEATURES: impersonation,token-exchange,admin-fine-grained-authz,account-api,scripts,upload-scripts,ciba,client-policies,declarative-user-profile,admin2
#      KC_FEATURES_DISABLED: impersonation

#      KC_HTTPS_PROTOCOLS: "TLSv1.3,TLSv1.2"

      PROXY_ADDRESS_FORWARDING: "true"

    # Enable remote debugging
      DEBUG: "true"
      DEBUG_PORT: "*:8787"

      # Append additional JVM Options besides the default JVM_OPTS
      # See: https://github.com/keycloak/keycloak/blob/main/distribution/server-x-dist/src/main/content/bin/kc.sh#L66
      JAVA_OPTS_APPEND: "-XX:+UseStringDeduplication"

      # Allow access via visualvm and jmc (remote jmx connection to localhost 8790 without ssl)
      # see https://docs.oracle.com/en/java/javase/11/management/monitoring-and-management-using-jmx-technology.html#GUID-D4CBA2D6-2E24-4856-A7D8-62B3DFFB76EA
      #JAVA_TOOL_OPTIONS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8790 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=true -Dcom.sun.management.jmxremote.password.file=/opt/keycloak/conf/jmxremote.password -Dcom.sun.management.jmxremote.ssl=false -XX:FlightRecorderOptions=stackdepth=256"
      JAVA_TOOL_OPTIONS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8790 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -XX:FlightRecorderOptions=stackdepth=256"
    mem_limit: 1024m
    mem_reservation: 1024m
    cpus: 2

    command:
      - "--verbose"
      - "start-dev"
      - "--http-enabled=true"
      - "--http-port=8080"
      - "--metrics-enabled=true"
      - "--health-enabled=true"
      - "--cache=local"
      - "--proxy=passthrough"
      - "--https-protocols=TLSv1.3,TLSv1.2"
      - "--spi-theme-cache-themes=false"
      - "--spi-theme-cache-templates=false"
      - "--spi-theme-static-max-age=-1"
      - "--spi-events-listener-email-exclude-events=LOGIN,LOGIN_ERROR,UPDATE_TOTP,REMOVE_TOTP"
      - "--spi-events-listener-email-include-events=UPDATE_PASSWORD"
      - "--spi-events-listener-jboss-logging-success-level=info"
      - "--spi-events-listener-jboss-logging-error-level=warn"
# Example for static overrides for .well-known/openid-configuration endpoint
#      - "--spi-well-known-openid-configuration-openid-configuration-override=/opt/keycloak/conf/openid-config.json"
#      - "--spi-well-known-openid-configuration-include-client-scopes=true"
# Workaround to allow logouts via old Keycloak Admin-Console
# see: org.keycloak.protocol.oidc.endpoints.LogoutEndpoint.logout(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)
      - "--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true"
#      - "--log-level=info,org.hibernate:debug"
#      - "--verbose"
    #      - "-Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.SimpleLog"
    extra_hosts:
      # 172.17.0.1 is host.docker.internal
      - "id.acme.test:172.17.0.1"
      - "apps.acme.test:172.17.0.1"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "127.0.0.1:8790:8790"
      - "127.0.0.1:8787:8787"
    volumes:
      - ../../../keycloak/themes:/opt/keycloak/themes:z
      - ../../../keycloak/config/profile.properties:/opt/keycloak/conf/profile.properties:z
      - ../../../keycloak/config/openid-config.json:/opt/keycloak/conf/openid-config.json:z
      - ../../../keycloak/config/jmxremote.password:/opt/keycloak/conf/jmxremote.password:ro
      - ../../../keycloak/imex:/opt/keycloak/imex:z
      - ./run/keycloakx/data:/opt/keycloak/data:z
      - ./run/keycloakx/logs:/opt/keycloak/logs:z
      - ./run/keycloakx/perf:/opt/keycloak/perf:z
# Add keycloak extensions
      - ../../../keycloak/extensions/target/extensions.jar:/opt/keycloak/providers/extensions.jar:z
# Add Keycloak.X specific extensions
      - ../../../keycloak/extensionsx/lib/db-scheduler-11.2.jar:/opt/keycloak/providers/db-scheduler-11.2.jar:z
      - ../../../keycloak/extensionsx/lib/micro-jdbc-0.3.jar:/opt/keycloak/providers/micro-jdbc-0.3.jar:z
      - ../../../keycloak/extensionsx/target/extensionsx.jar:/opt/keycloak/providers/extensionsx.jar:z
#      - ../../../keycloak/extensionsx/target/extensionsx-jar-with-dependencies.jar:/opt/keycloak/providers/extensionsx.jar:z
#      - ../../../keycloak/extensionsx/target/classes:/opt/keycloak/providers/extensionsx.jar:z
# Add third-party extensions
      - ./keycloak-ext/keycloak-metrics-spi-2.5.3-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-metrics-spi-2.5.3-SNAPSHOT.jar:z
      - ./keycloak-ext/keycloak-restrict-client-auth-17.0.0.jar:/opt/keycloak/providers/keycloak-restrict-client-auth-17.0.0.jar:z
      - ./keycloak-ext/keycloak-home-idp-discovery-18.0.0.jar:/opt/keycloak/providers/keycloak-home-idp-discovery.jar:z
#      - ./keycloak-ext/flyweight-user-storage-provider-extension-1.0.0.0-SNAPSHOT.jar:/opt/keycloak/providers/flyweight-user-storage-provider-extension-1.0.0.0-SNAPSHOT.jar:z
